### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by kalubin-awym** [sobyl/Solve-can-t-use-Anaconda-in-MacOS-Catalina#1]
$ /Users/-/anaconda3/bin/conda init bash
-bash: /Users/-/anaconda3/bin/conda: /Users/-/anaconda3/bin/python: bad interpreter: Operation not permitted

How to solve this problem?
thank you very much (my English poor)

**Comment by sobyl** [comment]
Try: 
$ xattr -l /Users/-/anaconda3/bin/conda
and 
$ xattr -d com.apple.quarantine /Users/-/anaconda3/bin/conda
I think this link https://stackoverflow.com/questions/9952612/mac-os-usr-bin-env-bad-interpreter-operation-not-permitted may help you.
